import { verifyEmailRequest, verificationResponse } from "#models/v1/authSystem/auth.js";
import { OpenApiSchemas } from "@packages/typed-rest/shared";

export const body = OpenApiSchemas.Request.Body.withPayload(verifyEmailRequest);

export const response = {
  200: OpenApiSchemas.Response.single(verificationResponse),
  ...OpenApiSchemas.Response.standardErrors(),
};

export const docs_summary = "Verify email with token";

export const docs_description =
  "Verifies a user's email using the token hash generated by Supabase.";

export const docs_body = {
  data: {
    token_hash: "The token hash from the email link",
    type: "The type of verification (signup, magiclink, etc.)",
  },
};

export const docs_response_200 =
  "Successfully verified email and returned user session";
