packages:
  - apps/*
  - packages/*
  - configs/*

ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - '@firebase/util'
  - '@scarf/scarf'
  - esbuild
  - protobufjs
  - sharp
  - supabase
  - unrs-resolver
