/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./supabase.types.js";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicRoleSchema = z.enum(["core_team", "support_team", "cadet"]);

export const publicAnnouncementRowSchema = z.object({
  banner_url: z.string().nullable(),
  content: z.string(),
  created_at: z.string(),
  creator_id: z.string(),
  id: z.string(),
  title: z.string(),
});

export const publicAnnouncementInsertSchema = z.object({
  banner_url: z.string().optional().nullable(),
  content: z.string(),
  created_at: z.string().optional(),
  creator_id: z.string(),
  id: z.string().optional(),
  title: z.string(),
});

export const publicAnnouncementUpdateSchema = z.object({
  banner_url: z.string().optional().nullable(),
  content: z.string().optional(),
  created_at: z.string().optional(),
  creator_id: z.string().optional(),
  id: z.string().optional(),
  title: z.string().optional(),
});

export const publicAnnouncementRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("announcement_creator_id_fkey"),
    columns: z.tuple([z.literal("creator_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profile"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicBadgeRowSchema = z.object({
  created_at: z.string(),
  creator_id: z.string(),
  description: z.string(),
  icon_url: z.string().nullable(),
  id: z.string(),
  title: z.string(),
});

export const publicBadgeInsertSchema = z.object({
  created_at: z.string().optional(),
  creator_id: z.string(),
  description: z.string(),
  icon_url: z.string().optional().nullable(),
  id: z.string().optional(),
  title: z.string(),
});

export const publicBadgeUpdateSchema = z.object({
  created_at: z.string().optional(),
  creator_id: z.string().optional(),
  description: z.string().optional(),
  icon_url: z.string().optional().nullable(),
  id: z.string().optional(),
  title: z.string().optional(),
});

export const publicBadgeRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("badge_creator_id_fkey"),
    columns: z.tuple([z.literal("creator_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profile"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicBadgeUserJunctionRowSchema = z.object({
  badge_id: z.string(),
  created_at: z.string(),
  id: z.string(),
  user_id: z.string(),
});

export const publicBadgeUserJunctionInsertSchema = z.object({
  badge_id: z.string(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  user_id: z.string(),
});

export const publicBadgeUserJunctionUpdateSchema = z.object({
  badge_id: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicBadgeUserJunctionRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("badge_user_junction_badge_id_fkey"),
    columns: z.tuple([z.literal("badge_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("badge"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("badge_user_junction_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profile"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicQuestionRowSchema = z.object({
  answer: z.number(),
  category: z.string().nullable(),
  created_at: z.string(),
  creator_id: z.string(),
  explanation: z.string().nullable(),
  id: z.string(),
  option_a: z.string(),
  option_b: z.string(),
  option_c: z.string().nullable(),
  option_d: z.string().nullable(),
  question: z.string(),
  schedule: z.string(),
  value: z.number(),
});

export const publicQuestionInsertSchema = z.object({
  answer: z.number(),
  category: z.string().optional().nullable(),
  created_at: z.string().optional(),
  creator_id: z.string(),
  explanation: z.string().optional().nullable(),
  id: z.string().optional(),
  option_a: z.string(),
  option_b: z.string(),
  option_c: z.string().optional().nullable(),
  option_d: z.string().optional().nullable(),
  question: z.string(),
  schedule: z.string(),
  value: z.number(),
});

export const publicQuestionUpdateSchema = z.object({
  answer: z.number().optional(),
  category: z.string().optional().nullable(),
  created_at: z.string().optional(),
  creator_id: z.string().optional(),
  explanation: z.string().optional().nullable(),
  id: z.string().optional(),
  option_a: z.string().optional(),
  option_b: z.string().optional(),
  option_c: z.string().optional().nullable(),
  option_d: z.string().optional().nullable(),
  question: z.string().optional(),
  schedule: z.string().optional(),
  value: z.number().optional(),
});

export const publicQuestionRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("question_creator_id_fkey"),
    columns: z.tuple([z.literal("creator_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profile"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicQuestionAnswerRowSchema = z.object({
  answer: z.number(),
  created_at: z.string(),
  id: z.string(),
  is_correct: z.boolean(),
  question_id: z.string(),
  user_id: z.string(),
});

export const publicQuestionAnswerInsertSchema = z.object({
  answer: z.number(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  is_correct: z.boolean(),
  question_id: z.string(),
  user_id: z.string(),
});

export const publicQuestionAnswerUpdateSchema = z.object({
  answer: z.number().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  is_correct: z.boolean().optional(),
  question_id: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicQuestionAnswerRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("question_answer_creator_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profile"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("question_answer_question_id_fkey"),
    columns: z.tuple([z.literal("question_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("question"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicQuestionStreakRowSchema = z.object({
  id: z.string(),
  streak: z.number(),
  user_id: z.string(),
});

export const publicQuestionStreakInsertSchema = z.object({
  id: z.string().optional(),
  streak: z.number().optional(),
  user_id: z.string(),
});

export const publicQuestionStreakUpdateSchema = z.object({
  id: z.string().optional(),
  streak: z.number().optional(),
  user_id: z.string().optional(),
});

export const publicQuestionStreakRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("question_streak_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profile"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicStudyJamRowSchema = z.object({
  created_at: z.string(),
  creator_id: z.string(),
  description: z.string(),
  id: z.string(),
  post_jam_activity_url: z.string().nullable(),
  post_jam_kit_url: z.string().nullable(),
  pre_jam_kit_url: z.string().nullable(),
  title: z.string(),
});

export const publicStudyJamInsertSchema = z.object({
  created_at: z.string().optional(),
  creator_id: z.string(),
  description: z.string(),
  id: z.string().optional(),
  post_jam_activity_url: z.string().optional().nullable(),
  post_jam_kit_url: z.string().optional().nullable(),
  pre_jam_kit_url: z.string().optional().nullable(),
  title: z.string(),
});

export const publicStudyJamUpdateSchema = z.object({
  created_at: z.string().optional(),
  creator_id: z.string().optional(),
  description: z.string().optional(),
  id: z.string().optional(),
  post_jam_activity_url: z.string().optional().nullable(),
  post_jam_kit_url: z.string().optional().nullable(),
  pre_jam_kit_url: z.string().optional().nullable(),
  title: z.string().optional(),
});

export const publicStudyJamRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("study_jam_creator_id_fkey"),
    columns: z.tuple([z.literal("creator_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profile"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicTokenRowSchema = z.object({
  claimed_at: z.string().nullable(),
  claimed_by_id: z.string().nullable(),
  code: z.string(),
  created_at: z.string(),
  creator_id: z.string(),
  id: z.string(),
  is_claimed: z.boolean(),
  is_voided: z.boolean(),
  template_id: z.string(),
});

export const publicTokenInsertSchema = z.object({
  claimed_at: z.string().optional().nullable(),
  claimed_by_id: z.string().optional().nullable(),
  code: z.string(),
  created_at: z.string().optional(),
  creator_id: z.string(),
  id: z.string().optional(),
  is_claimed: z.boolean().optional(),
  is_voided: z.boolean().optional(),
  template_id: z.string(),
});

export const publicTokenUpdateSchema = z.object({
  claimed_at: z.string().optional().nullable(),
  claimed_by_id: z.string().optional().nullable(),
  code: z.string().optional(),
  created_at: z.string().optional(),
  creator_id: z.string().optional(),
  id: z.string().optional(),
  is_claimed: z.boolean().optional(),
  is_voided: z.boolean().optional(),
  template_id: z.string().optional(),
});

export const publicTokenRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("token_claimed_by_id_fkey"),
    columns: z.tuple([z.literal("claimed_by_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profile"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("token_creator_id_fkey"),
    columns: z.tuple([z.literal("creator_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profile"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("token_template_id_fkey"),
    columns: z.tuple([z.literal("template_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("token_template"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicTokenTemplateRowSchema = z.object({
  created_at: z.string(),
  creator_id: z.string(),
  description: z.string(),
  id: z.string(),
  title: z.string(),
  value: z.number(),
});

export const publicTokenTemplateInsertSchema = z.object({
  created_at: z.string().optional(),
  creator_id: z.string(),
  description: z.string(),
  id: z.string().optional(),
  title: z.string(),
  value: z.number(),
});

export const publicTokenTemplateUpdateSchema = z.object({
  created_at: z.string().optional(),
  creator_id: z.string().optional(),
  description: z.string().optional(),
  id: z.string().optional(),
  title: z.string().optional(),
  value: z.number().optional(),
});

export const publicTokenTemplateRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("token_template_creator_id_fkey"),
    columns: z.tuple([z.literal("creator_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profile"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicUserProfileRowSchema = z.object({
  avatar_url: z.string().nullable(),
  created_at: z.string(),
  display_name: z.string(),
  email: z.string(),
  id: z.string(),
});

export const publicUserProfileInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  display_name: z.string(),
  email: z.string(),
  id: z.string(),
});

export const publicUserProfileUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  display_name: z.string().optional(),
  email: z.string().optional(),
  id: z.string().optional(),
});

export const publicUserRoleRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  role: z.string(),
  user_id: z.string(),
});

export const publicUserRoleInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  role: z.string().optional(),
  user_id: z.string(),
});

export const publicUserRoleUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  role: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicUserRoleRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("user_role_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profile"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicWalletRowSchema = z.object({
  balance: z.number(),
  created_at: z.string(),
  id: z.string(),
  user_id: z.string(),
});

export const publicWalletInsertSchema = z.object({
  balance: z.number().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  user_id: z.string(),
});

export const publicWalletUpdateSchema = z.object({
  balance: z.number().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicWalletRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("wallet_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_profile"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicWalletTransactionRowSchema = z.object({
  amount: z.number(),
  created_at: z.string(),
  id: z.string(),
  source_id: z.string(),
  source_type: z.string(),
  wallet_id: z.string(),
});

export const publicWalletTransactionInsertSchema = z.object({
  amount: z.number(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  source_id: z.string(),
  source_type: z.string(),
  wallet_id: z.string(),
});

export const publicWalletTransactionUpdateSchema = z.object({
  amount: z.number().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  source_id: z.string().optional(),
  source_type: z.string().optional(),
  wallet_id: z.string().optional(),
});

export const publicWalletTransactionRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("wallet_transactions_wallet_id_fkey"),
    columns: z.tuple([z.literal("wallet_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("wallet"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);
