/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./supabase.types";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicArticleRowSchema = z.object({
  author_id: z.string().nullable(),
  body: z.string().nullable(),
  created_at: z.string(),
  id: z.string(),
  is_published: z.boolean(),
  published_at: z.string().nullable(),
  related_event_id: z.string().nullable(),
  title: z.string(),
  updated_at: z.string(),
});

export const publicArticleInsertSchema = z.object({
  author_id: z.string().optional().nullable(),
  body: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  is_published: z.boolean().optional(),
  published_at: z.string().optional().nullable(),
  related_event_id: z.string().optional().nullable(),
  title: z.string(),
  updated_at: z.string().optional(),
});

export const publicArticleUpdateSchema = z.object({
  author_id: z.string().optional().nullable(),
  body: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  is_published: z.boolean().optional(),
  published_at: z.string().optional().nullable(),
  related_event_id: z.string().optional().nullable(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicArticleRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("article_author_id_fkey"),
    columns: z.tuple([z.literal("author_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("article_related_event_id_fkey"),
    columns: z.tuple([z.literal("related_event_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("event"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicArticleCommentRowSchema = z.object({
  article_id: z.string().nullable(),
  body: z.string(),
  created_at: z.string(),
  id: z.string(),
  updated_at: z.string(),
  user_id: z.string().nullable(),
});

export const publicArticleCommentInsertSchema = z.object({
  article_id: z.string().optional().nullable(),
  body: z.string(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional().nullable(),
});

export const publicArticleCommentUpdateSchema = z.object({
  article_id: z.string().optional().nullable(),
  body: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional().nullable(),
});

export const publicArticleCommentRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("article_comment_article_id_fkey"),
    columns: z.tuple([z.literal("article_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("article"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicEventRowSchema = z.object({
  attendance_points: z.number(),
  attendees_count: z.number(),
  category: z.string().nullable(),
  created_at: z.string(),
  creator_id: z.string().nullable(),
  description: z.string().nullable(),
  end_date: z.string().nullable(),
  id: z.string(),
  start_date: z.string().nullable(),
  title: z.string(),
  updated_at: z.string(),
  venue: z.string().nullable(),
});

export const publicEventInsertSchema = z.object({
  attendance_points: z.number().optional(),
  attendees_count: z.number().optional(),
  category: z.string().optional().nullable(),
  created_at: z.string().optional(),
  creator_id: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  end_date: z.string().optional().nullable(),
  id: z.string().optional(),
  start_date: z.string().optional().nullable(),
  title: z.string(),
  updated_at: z.string().optional(),
  venue: z.string().optional().nullable(),
});

export const publicEventUpdateSchema = z.object({
  attendance_points: z.number().optional(),
  attendees_count: z.number().optional(),
  category: z.string().optional().nullable(),
  created_at: z.string().optional(),
  creator_id: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  end_date: z.string().optional().nullable(),
  id: z.string().optional(),
  start_date: z.string().optional().nullable(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
  venue: z.string().optional().nullable(),
});

export const publicEventRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("events_creator_id_fkey"),
    columns: z.tuple([z.literal("creator_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicEventAttendanceRowSchema = z.object({
  checkin_method: z.string(),
  created_at: z.string(),
  event_id: z.string(),
  id: z.string(),
  is_present: z.boolean(),
  user_id: z.string(),
});

export const publicEventAttendanceInsertSchema = z.object({
  checkin_method: z.string(),
  created_at: z.string().optional(),
  event_id: z.string(),
  id: z.string().optional(),
  is_present: z.boolean().optional(),
  user_id: z.string(),
});

export const publicEventAttendanceUpdateSchema = z.object({
  checkin_method: z.string().optional(),
  created_at: z.string().optional(),
  event_id: z.string().optional(),
  id: z.string().optional(),
  is_present: z.boolean().optional(),
  user_id: z.string().optional(),
});

export const publicEventAttendanceRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("event_attendance_event_id_fkey"),
    columns: z.tuple([z.literal("event_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("event"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("event_attendance_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicExternalResourceRowSchema = z.object({
  created_at: z.string(),
  description: z.string().nullable(),
  id: z.string(),
  resource_url: z.string(),
  title: z.string(),
  updated_at: z.string(),
  uploader_id: z.string(),
});

export const publicExternalResourceInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  resource_url: z.string(),
  title: z.string(),
  updated_at: z.string().optional(),
  uploader_id: z.string(),
});

export const publicExternalResourceUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  resource_url: z.string().optional(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
  uploader_id: z.string().optional(),
});

export const publicExternalResourceRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("resource_uploader_id_fkey"),
    columns: z.tuple([z.literal("uploader_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicNfcCardRowSchema = z.object({
  activated_at: z.string().nullable(),
  created_at: z.string(),
  id: z.string(),
  status: z.string(),
  user_id: z.string().nullable(),
});

export const publicNfcCardInsertSchema = z.object({
  activated_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string(),
  status: z.string().optional(),
  user_id: z.string().optional().nullable(),
});

export const publicNfcCardUpdateSchema = z.object({
  activated_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  status: z.string().optional(),
  user_id: z.string().optional().nullable(),
});

export const publicNfcCardRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("nfc_card_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicNfcCardTransactionRowSchema = z.object({
  card_id: z.string(),
  created_at: z.string(),
  event_type: z.string(),
  id: z.string(),
  metadata: jsonSchema.nullable(),
  scanner_id: z.string().nullable(),
});

export const publicNfcCardTransactionInsertSchema = z.object({
  card_id: z.string(),
  created_at: z.string().optional(),
  event_type: z.string(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  scanner_id: z.string().optional().nullable(),
});

export const publicNfcCardTransactionUpdateSchema = z.object({
  card_id: z.string().optional(),
  created_at: z.string().optional(),
  event_type: z.string().optional(),
  id: z.string().optional(),
  metadata: jsonSchema.optional().nullable(),
  scanner_id: z.string().optional().nullable(),
});

export const publicNfcCardTransactionRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("nfc_card_transaction_card_id_fkey"),
    columns: z.tuple([z.literal("card_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("nfc_card"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("nfc_card_transaction_scanner_id_fkey"),
    columns: z.tuple([z.literal("scanner_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicResourceTagRowSchema = z.object({
  id: z.string(),
  tag_name: z.string(),
});

export const publicResourceTagInsertSchema = z.object({
  id: z.string().optional(),
  tag_name: z.string(),
});

export const publicResourceTagUpdateSchema = z.object({
  id: z.string().optional(),
  tag_name: z.string().optional(),
});

export const publicResourceTagJunctionRowSchema = z.object({
  id: z.string(),
  resource_id: z.string(),
  resource_tag_id: z.string(),
});

export const publicResourceTagJunctionInsertSchema = z.object({
  id: z.string().optional(),
  resource_id: z.string(),
  resource_tag_id: z.string(),
});

export const publicResourceTagJunctionUpdateSchema = z.object({
  id: z.string().optional(),
  resource_id: z.string().optional(),
  resource_tag_id: z.string().optional(),
});

export const publicResourceTagJunctionRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("resource_tag_junction_resource_id_fkey"),
    columns: z.tuple([z.literal("resource_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("external_resource"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("resource_tag_junction_resource_tag_id_fkey"),
    columns: z.tuple([z.literal("resource_tag_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("resource_tag"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicRewardRowSchema = z.object({
  created_at: z.string(),
  description: z.string(),
  id: z.string(),
  is_claimed: z.boolean(),
  title: z.string(),
  user_id: z.string(),
  value: z.number(),
});

export const publicRewardInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string(),
  id: z.string().optional(),
  is_claimed: z.boolean().optional(),
  title: z.string(),
  user_id: z.string(),
  value: z.number().optional(),
});

export const publicRewardUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional(),
  id: z.string().optional(),
  is_claimed: z.boolean().optional(),
  title: z.string().optional(),
  user_id: z.string().optional(),
  value: z.number().optional(),
});

export const publicRewardRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("reward_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicStudyJamRowSchema = z.object({
  created_at: z.string(),
  description: z.string(),
  id: z.string(),
  recording_url: z.string(),
  summary: z.string(),
  title: z.string(),
});

export const publicStudyJamInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string(),
  id: z.string().optional(),
  recording_url: z.string(),
  summary: z.string(),
  title: z.string(),
});

export const publicStudyJamUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional(),
  id: z.string().optional(),
  recording_url: z.string().optional(),
  summary: z.string().optional(),
  title: z.string().optional(),
});

export const publicTeamRowSchema = z.object({
  description: z.string(),
  id: z.string(),
  name: z.string(),
});

export const publicTeamInsertSchema = z.object({
  description: z.string(),
  id: z.string().optional(),
  name: z.string(),
});

export const publicTeamUpdateSchema = z.object({
  description: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
});

export const publicTeamMemberRowSchema = z.object({
  id: z.string(),
  role: z.string(),
  team_id: z.string(),
  user_id: z.string(),
});

export const publicTeamMemberInsertSchema = z.object({
  id: z.string().optional(),
  role: z.string(),
  team_id: z.string(),
  user_id: z.string(),
});

export const publicTeamMemberUpdateSchema = z.object({
  id: z.string().optional(),
  role: z.string().optional(),
  team_id: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicTeamMemberRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("team_member_team_id_fkey"),
    columns: z.tuple([z.literal("team_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("team"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("team_member_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicUserRowSchema = z.object({
  avatar_url: z.string().nullable(),
  created_at: z.string(),
  display_name: z.string(),
  email: z.string(),
  first_name: z.string().nullable(),
  gdg_id: z.string(),
  id: z.string(),
  last_name: z.string().nullable(),
  status: z.string(),
  updated_at: z.string(),
});

export const publicUserInsertSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  display_name: z.string(),
  email: z.string(),
  first_name: z.string().optional().nullable(),
  gdg_id: z.string().optional(),
  id: z.string().optional(),
  last_name: z.string().optional().nullable(),
  status: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicUserUpdateSchema = z.object({
  avatar_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  display_name: z.string().optional(),
  email: z.string().optional(),
  first_name: z.string().optional().nullable(),
  gdg_id: z.string().optional(),
  id: z.string().optional(),
  last_name: z.string().optional().nullable(),
  status: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicUserCertificateRowSchema = z.object({
  description: z.string(),
  id: z.string(),
  image_url: z.string(),
  title: z.string(),
  user_id: z.string(),
});

export const publicUserCertificateInsertSchema = z.object({
  description: z.string(),
  id: z.string().optional(),
  image_url: z.string(),
  title: z.string(),
  user_id: z.string(),
});

export const publicUserCertificateUpdateSchema = z.object({
  description: z.string().optional(),
  id: z.string().optional(),
  image_url: z.string().optional(),
  title: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicUserCertificateRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("user_certificate_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicUserProfileRowSchema = z.object({
  bio: z.string().nullable(),
  created_at: z.string(),
  github_url: z.string().nullable(),
  id: z.string(),
  is_public: z.boolean(),
  linkedin_url: z.string().nullable(),
  portfolio_url: z.string().nullable(),
  program: z.string().nullable(),
  skills_summary: z.string().nullable(),
  updated_at: z.string(),
  user_id: z.string(),
  year_level: z.number().nullable(),
});

export const publicUserProfileInsertSchema = z.object({
  bio: z.string().optional().nullable(),
  created_at: z.string().optional(),
  github_url: z.string().optional().nullable(),
  id: z.string().optional(),
  is_public: z.boolean().optional(),
  linkedin_url: z.string().optional().nullable(),
  portfolio_url: z.string().optional().nullable(),
  program: z.string().optional().nullable(),
  skills_summary: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  user_id: z.string(),
  year_level: z.number().optional().nullable(),
});

export const publicUserProfileUpdateSchema = z.object({
  bio: z.string().optional().nullable(),
  created_at: z.string().optional(),
  github_url: z.string().optional().nullable(),
  id: z.string().optional(),
  is_public: z.boolean().optional(),
  linkedin_url: z.string().optional().nullable(),
  portfolio_url: z.string().optional().nullable(),
  program: z.string().optional().nullable(),
  skills_summary: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
  year_level: z.number().optional().nullable(),
});

export const publicUserProfileRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("user_profile_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicUserProjectRowSchema = z.object({
  created_at: z.string(),
  demo_url: z.string().nullable(),
  description: z.string().nullable(),
  id: z.string(),
  repo_url: z.string().nullable(),
  tech_stack: z.string().nullable(),
  title: z.string(),
  user_id: z.string(),
});

export const publicUserProjectInsertSchema = z.object({
  created_at: z.string().optional(),
  demo_url: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  repo_url: z.string().optional().nullable(),
  tech_stack: z.string().optional().nullable(),
  title: z.string(),
  user_id: z.string(),
});

export const publicUserProjectUpdateSchema = z.object({
  created_at: z.string().optional(),
  demo_url: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  repo_url: z.string().optional().nullable(),
  tech_stack: z.string().optional().nullable(),
  title: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicUserProjectRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("user_project_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicUserRoleRowSchema = z.object({
  description: z.string(),
  id: z.string(),
  role_name: z.string(),
});

export const publicUserRoleInsertSchema = z.object({
  description: z.string(),
  id: z.string().optional(),
  role_name: z.string(),
});

export const publicUserRoleUpdateSchema = z.object({
  description: z.string().optional(),
  id: z.string().optional(),
  role_name: z.string().optional(),
});

export const publicUserRoleJunctionRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  role_id: z.string(),
  user_id: z.string(),
});

export const publicUserRoleJunctionInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  role_id: z.string(),
  user_id: z.string(),
});

export const publicUserRoleJunctionUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  role_id: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicUserRoleJunctionRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("user_role_junction_role_id_fkey"),
    columns: z.tuple([z.literal("role_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_role"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("user_role_junction_user_id_fkey1"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicUserRolePermissionRowSchema = z.object({
  can_delete: z.boolean(),
  can_read: z.boolean(),
  can_update: z.boolean(),
  can_write: z.boolean(),
  id: z.string(),
  resource_name: z.string(),
  user_role_id: z.string(),
});

export const publicUserRolePermissionInsertSchema = z.object({
  can_delete: z.boolean(),
  can_read: z.boolean(),
  can_update: z.boolean(),
  can_write: z.boolean(),
  id: z.string().optional(),
  resource_name: z.string(),
  user_role_id: z.string(),
});

export const publicUserRolePermissionUpdateSchema = z.object({
  can_delete: z.boolean().optional(),
  can_read: z.boolean().optional(),
  can_update: z.boolean().optional(),
  can_write: z.boolean().optional(),
  id: z.string().optional(),
  resource_name: z.string().optional(),
  user_role_id: z.string().optional(),
});

export const publicUserRolePermissionRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("user_role_permission_user_role_id_fkey"),
    columns: z.tuple([z.literal("user_role_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_role"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicUserSettingsRowSchema = z.object({
  color_theme: z.boolean(),
  id: z.string(),
  user_id: z.string(),
});

export const publicUserSettingsInsertSchema = z.object({
  color_theme: z.boolean(),
  id: z.string().optional(),
  user_id: z.string(),
});

export const publicUserSettingsUpdateSchema = z.object({
  color_theme: z.boolean().optional(),
  id: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicUserSettingsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("user_settings_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicWalletRowSchema = z.object({
  balance: z.number(),
  created_at: z.string(),
  id: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const publicWalletInsertSchema = z.object({
  balance: z.number(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const publicWalletUpdateSchema = z.object({
  balance: z.number().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicWalletRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("wallet_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicWalletTransactionRowSchema = z.object({
  amount: z.number(),
  created_at: z.string(),
  id: z.string(),
  source_id: z.string(),
  source_type: z.string(),
  wallet_id: z.string(),
});

export const publicWalletTransactionInsertSchema = z.object({
  amount: z.number().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  source_id: z.string(),
  source_type: z.string(),
  wallet_id: z.string(),
});

export const publicWalletTransactionUpdateSchema = z.object({
  amount: z.number().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  source_id: z.string().optional(),
  source_type: z.string().optional(),
  wallet_id: z.string().optional(),
});

export const publicWalletTransactionRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("wallet_transaction_wallet_id_fkey"),
    columns: z.tuple([z.literal("wallet_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("wallet"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);
