/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./supabase.types";

export const publicNfcCardStatusSchema = z.enum([
  "issued",
  "activated",
  "suspended",
  "revoked",
]);

export const publicSparkmatesSourceSchema = z.enum([
  "nfc_card",
  "qr_code",
  "direct_link",
]);

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicAnalyticsNfcCardScansRowSchema = z.object({
  date: z.string(),
  id: z.string(),
  nfcCardId: z.string().nullable(),
  scanContext: z.string().nullable(),
  scannerId: z.string().nullable(),
});

export const publicAnalyticsNfcCardScansInsertSchema = z.object({
  date: z.string().optional(),
  id: z.string().optional(),
  nfcCardId: z.string().optional().nullable(),
  scanContext: z.string().optional().nullable(),
  scannerId: z.string().optional().nullable(),
});

export const publicAnalyticsNfcCardScansUpdateSchema = z.object({
  date: z.string().optional(),
  id: z.string().optional(),
  nfcCardId: z.string().optional().nullable(),
  scanContext: z.string().optional().nullable(),
  scannerId: z.string().optional().nullable(),
});

export const publicAnalyticsNfcCardScansRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("analytics_nfc_card_scans_nfcCardId_fkey"),
    columns: z.tuple([z.literal("nfcCardId")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("nfc_cards"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicAnalyticsProfileViewsRowSchema = z.object({
  date: z.string(),
  id: z.string(),
  profileGdgId: z.string().nullable(),
  source: z.string().nullable(),
  user_agent: z.string().nullable(),
  viewerGdgId: z.string().nullable(),
});

export const publicAnalyticsProfileViewsInsertSchema = z.object({
  date: z.string().optional(),
  id: z.string().optional(),
  profileGdgId: z.string().optional().nullable(),
  source: z.string().optional().nullable(),
  user_agent: z.string().optional().nullable(),
  viewerGdgId: z.string().optional().nullable(),
});

export const publicAnalyticsProfileViewsUpdateSchema = z.object({
  date: z.string().optional(),
  id: z.string().optional(),
  profileGdgId: z.string().optional().nullable(),
  source: z.string().optional().nullable(),
  user_agent: z.string().optional().nullable(),
  viewerGdgId: z.string().optional().nullable(),
});

export const publicAnalyticsProfileViewsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("analytics_profile_views_profile_gdg_id_fkey"),
    columns: z.tuple([z.literal("profileGdgId")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("gdg_members"),
    referencedColumns: z.tuple([z.literal("gdg_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("analytics_profile_views_viewerGdgId_fkey"),
    columns: z.tuple([z.literal("viewerGdgId")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("gdg_members"),
    referencedColumns: z.tuple([z.literal("gdg_id")]),
  }),
]);

export const publicArticleRowSchema = z.object({
  author_id: z.string().nullable(),
  content: z.string().nullable(),
  created_at: z.string(),
  description: z.string().nullable(),
  eventId: z.string().nullable(),
  id: z.string(),
  is_published: z.boolean(),
  published_at: z.string().nullable(),
  thumbnail_url: z.string().nullable(),
  title: z.string(),
  updated_at: z.string(),
});

export const publicArticleInsertSchema = z.object({
  author_id: z.string().optional().nullable(),
  content: z.string().optional().nullable(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  eventId: z.string().optional().nullable(),
  id: z.string().optional(),
  is_published: z.boolean().optional(),
  published_at: z.string().optional().nullable(),
  thumbnail_url: z.string().optional().nullable(),
  title: z.string(),
  updated_at: z.string().optional(),
});

export const publicArticleUpdateSchema = z.object({
  author_id: z.string().optional().nullable(),
  content: z.string().optional().nullable(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  eventId: z.string().optional().nullable(),
  id: z.string().optional(),
  is_published: z.boolean().optional(),
  published_at: z.string().optional().nullable(),
  thumbnail_url: z.string().optional().nullable(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicDpDownloadAnalyticsRowSchema = z.object({
  created_at: z.string(),
  downloaded_at: z.string(),
  event_slug: z.string(),
  frame_id: z.string(),
  id: z.number(),
  source_path: z.string().nullable(),
  user_agent: z.string().nullable(),
});

export const publicDpDownloadAnalyticsInsertSchema = z.object({
  created_at: z.string().optional(),
  downloaded_at: z.string().optional(),
  event_slug: z.string(),
  frame_id: z.string(),
  id: z.never().optional(),
  source_path: z.string().optional().nullable(),
  user_agent: z.string().optional().nullable(),
});

export const publicDpDownloadAnalyticsUpdateSchema = z.object({
  created_at: z.string().optional(),
  downloaded_at: z.string().optional(),
  event_slug: z.string().optional(),
  frame_id: z.string().optional(),
  id: z.never().optional(),
  source_path: z.string().optional().nullable(),
  user_agent: z.string().optional().nullable(),
});

export const publicEventRowSchema = z.object({
  attendance_points: z.number(),
  attendees_count: z.number(),
  bevy_preview_url: z.string().nullable(),
  category: z.string().nullable(),
  created_at: z.string(),
  creator_id: z.string().nullable(),
  description: z.string().nullable(),
  end_date: z.string().nullable(),
  gdg_event_id: z.number().nullable(),
  id: z.string(),
  max_capacity: z.string().nullable(),
  rsvp: z.number().nullable(),
  short_description: z.string().nullable(),
  speakers: z.array(z.string()).nullable(),
  start_date: z.string().nullable(),
  tags: z.string().nullable(),
  team_id: z.string().nullable(),
  thumbnail_url: z.string().nullable(),
  title: z.string(),
  type: z.string().nullable(),
  updated_at: z.string(),
  venue: z.string().nullable(),
});

export const publicEventInsertSchema = z.object({
  attendance_points: z.number().optional(),
  attendees_count: z.number().optional(),
  bevy_preview_url: z.string().optional().nullable(),
  category: z.string().optional().nullable(),
  created_at: z.string().optional(),
  creator_id: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  end_date: z.string().optional().nullable(),
  gdg_event_id: z.number().optional().nullable(),
  id: z.string().optional(),
  max_capacity: z.string().optional().nullable(),
  rsvp: z.number().optional().nullable(),
  short_description: z.string().optional().nullable(),
  speakers: z.array(z.string()).optional().nullable(),
  start_date: z.string().optional().nullable(),
  tags: z.string().optional().nullable(),
  team_id: z.string().optional().nullable(),
  thumbnail_url: z.string().optional().nullable(),
  title: z.string(),
  type: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  venue: z.string().optional().nullable(),
});

export const publicEventUpdateSchema = z.object({
  attendance_points: z.number().optional(),
  attendees_count: z.number().optional(),
  bevy_preview_url: z.string().optional().nullable(),
  category: z.string().optional().nullable(),
  created_at: z.string().optional(),
  creator_id: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  end_date: z.string().optional().nullable(),
  gdg_event_id: z.number().optional().nullable(),
  id: z.string().optional(),
  max_capacity: z.string().optional().nullable(),
  rsvp: z.number().optional().nullable(),
  short_description: z.string().optional().nullable(),
  speakers: z.array(z.string()).optional().nullable(),
  start_date: z.string().optional().nullable(),
  tags: z.string().optional().nullable(),
  team_id: z.string().optional().nullable(),
  thumbnail_url: z.string().optional().nullable(),
  title: z.string().optional(),
  type: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  venue: z.string().optional().nullable(),
});

export const publicEventRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("event_gdg_event_id_fkey"),
    columns: z.tuple([z.literal("gdg_event_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("scraped_gdg_events"),
    referencedColumns: z.tuple([z.literal("gdg_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("event_team_id_fkey"),
    columns: z.tuple([z.literal("team_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("team"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicEventAttendanceRowSchema = z.object({
  checkin_method: z.string(),
  created_at: z.string(),
  event_id: z.string(),
  id: z.string(),
  is_present: z.boolean(),
  user_id: z.string(),
});

export const publicEventAttendanceInsertSchema = z.object({
  checkin_method: z.string(),
  created_at: z.string().optional(),
  event_id: z.string(),
  id: z.string().optional(),
  is_present: z.boolean().optional(),
  user_id: z.string(),
});

export const publicEventAttendanceUpdateSchema = z.object({
  checkin_method: z.string().optional(),
  created_at: z.string().optional(),
  event_id: z.string().optional(),
  id: z.string().optional(),
  is_present: z.boolean().optional(),
  user_id: z.string().optional(),
});

export const publicEventAttendanceRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("event_attendance_event_id_fkey"),
    columns: z.tuple([z.literal("event_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("event"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicFileRecordRowSchema = z.object({
  created_at: z.string(),
  deleted_at: z.string().nullable(),
  file_description: z.string().nullable(),
  file_name: z.string().nullable(),
  file_path: z.string().nullable(),
  file_type: z.string(),
  folder_id: z.string().nullable(),
  id: z.string(),
  preview_url: z.string().nullable(),
  storage_ref: z.string().nullable(),
  updated_at: z.string(),
});

export const publicFileRecordInsertSchema = z.object({
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  file_description: z.string().optional().nullable(),
  file_name: z.string().optional().nullable(),
  file_path: z.string().optional().nullable(),
  file_type: z.string().optional(),
  folder_id: z.string().optional().nullable(),
  id: z.string().optional(),
  preview_url: z.string().optional().nullable(),
  storage_ref: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicFileRecordUpdateSchema = z.object({
  created_at: z.string().optional(),
  deleted_at: z.string().optional().nullable(),
  file_description: z.string().optional().nullable(),
  file_name: z.string().optional().nullable(),
  file_path: z.string().optional().nullable(),
  file_type: z.string().optional(),
  folder_id: z.string().optional().nullable(),
  id: z.string().optional(),
  preview_url: z.string().optional().nullable(),
  storage_ref: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicFileRecordRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("file_record_folder_id_fkey"),
    columns: z.tuple([z.literal("folder_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("filesystem_folder"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicFilesystemFolderRowSchema = z.object({
  created_at: z.string(),
  description: z.string().nullable(),
  id: z.string(),
  name: z.string(),
  parent_id: z.string().nullable(),
  updated_at: z.string(),
});

export const publicFilesystemFolderInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string(),
  parent_id: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicFilesystemFolderUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  name: z.string().optional(),
  parent_id: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicFilesystemFolderRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("filesystem_folder_parent_id_fkey"),
    columns: z.tuple([z.literal("parent_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("filesystem_folder"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicGdgMembersRowSchema = z.object({
  avatar_image_url: z.string().nullable(),
  bio: z.string().nullable(),
  created_at: z.string().nullable(),
  department: z.string().nullable(),
  display_name: z.string().nullable(),
  email: z.string(),
  first_name: z.string().nullable(),
  gdg_id: z.string(),
  github_url: z.string().nullable(),
  is_public: z.boolean().nullable(),
  last_name: z.string().nullable(),
  learning_interests: z.string().nullable(),
  linkedin_url: z.string().nullable(),
  membership_type: z.string().nullable(),
  middle_name: z.string().nullable(),
  nickname: z.string().nullable(),
  other_links: z.string().nullable(),
  portfolio_url: z.string().nullable(),
  program: z.string().nullable(),
  section_order: z.string().nullable(),
  skills_summary: z.string().nullable(),
  suffix: z.string().nullable(),
  technical_skills: z.string().nullable(),
  tools_and_technologies: z.string().nullable(),
  updated_at: z.string().nullable(),
  year_level: z.number().nullable(),
});

export const publicGdgMembersInsertSchema = z.object({
  avatar_image_url: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  department: z.string().optional().nullable(),
  display_name: z.string().optional().nullable(),
  email: z.string(),
  first_name: z.string().optional().nullable(),
  gdg_id: z.string(),
  github_url: z.string().optional().nullable(),
  is_public: z.boolean().optional().nullable(),
  last_name: z.string().optional().nullable(),
  learning_interests: z.string().optional().nullable(),
  linkedin_url: z.string().optional().nullable(),
  membership_type: z.string().optional().nullable(),
  middle_name: z.string().optional().nullable(),
  nickname: z.string().optional().nullable(),
  other_links: z.string().optional().nullable(),
  portfolio_url: z.string().optional().nullable(),
  program: z.string().optional().nullable(),
  section_order: z.string().optional().nullable(),
  skills_summary: z.string().optional().nullable(),
  suffix: z.string().optional().nullable(),
  technical_skills: z.string().optional().nullable(),
  tools_and_technologies: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  year_level: z.number().optional().nullable(),
});

export const publicGdgMembersUpdateSchema = z.object({
  avatar_image_url: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  department: z.string().optional().nullable(),
  display_name: z.string().optional().nullable(),
  email: z.string().optional(),
  first_name: z.string().optional().nullable(),
  gdg_id: z.string().optional(),
  github_url: z.string().optional().nullable(),
  is_public: z.boolean().optional().nullable(),
  last_name: z.string().optional().nullable(),
  learning_interests: z.string().optional().nullable(),
  linkedin_url: z.string().optional().nullable(),
  membership_type: z.string().optional().nullable(),
  middle_name: z.string().optional().nullable(),
  nickname: z.string().optional().nullable(),
  other_links: z.string().optional().nullable(),
  portfolio_url: z.string().optional().nullable(),
  program: z.string().optional().nullable(),
  section_order: z.string().optional().nullable(),
  skills_summary: z.string().optional().nullable(),
  suffix: z.string().optional().nullable(),
  technical_skills: z.string().optional().nullable(),
  tools_and_technologies: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  year_level: z.number().optional().nullable(),
});

export const publicGdgMerchRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  image_url: z.string().nullable(),
  name: z.string().nullable(),
  points_cost: z.number().nullable(),
  stock: z.string().nullable(),
  updated_at: z.string().nullable(),
});

export const publicGdgMerchInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  points_cost: z.number().optional().nullable(),
  stock: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicGdgMerchUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  points_cost: z.number().optional().nullable(),
  stock: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicLearningResourceRowSchema = z.object({
  created_at: z.string(),
  description: z.string().nullable(),
  event_id: z.string().nullable(),
  id: z.string(),
  tags: jsonSchema.nullable(),
  team_id: z.string().nullable(),
  thumbnail_url: z.string().nullable(),
  title: z.string(),
  updated_at: z.string(),
  url: z.string(),
});

export const publicLearningResourceInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  event_id: z.string().optional().nullable(),
  id: z.string().optional(),
  tags: jsonSchema.optional().nullable(),
  team_id: z.string().optional().nullable(),
  thumbnail_url: z.string().optional().nullable(),
  title: z.string(),
  updated_at: z.string().optional(),
  url: z.string(),
});

export const publicLearningResourceUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  event_id: z.string().optional().nullable(),
  id: z.string().optional(),
  tags: jsonSchema.optional().nullable(),
  team_id: z.string().optional().nullable(),
  thumbnail_url: z.string().optional().nullable(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
  url: z.string().optional(),
});

export const publicLearningResourceRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("learning_resource_event_id_fkey"),
    columns: z.tuple([z.literal("event_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("event"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("learning_resource_team_id_fkey"),
    columns: z.tuple([z.literal("team_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("team"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicMemberProjectsRowSchema = z.object({
  createdAt: z.string(),
  description: z.string().nullable(),
  endDate: z.string().nullable(),
  id: z.string(),
  mainImageUrl: z.string().nullable(),
  memberGdgId: z.string().nullable(),
  secondaryImageUrl: z.string().nullable(),
  startDate: z.string().nullable(),
  tertiaryImageUrl: z.string().nullable(),
  title: z.string().nullable(),
  updatedAt: z.string().nullable(),
});

export const publicMemberProjectsInsertSchema = z.object({
  createdAt: z.string().optional(),
  description: z.string().optional().nullable(),
  endDate: z.string().optional().nullable(),
  id: z.string().optional(),
  mainImageUrl: z.string().optional().nullable(),
  memberGdgId: z.string().optional().nullable(),
  secondaryImageUrl: z.string().optional().nullable(),
  startDate: z.string().optional().nullable(),
  tertiaryImageUrl: z.string().optional().nullable(),
  title: z.string().optional().nullable(),
  updatedAt: z.string().optional().nullable(),
});

export const publicMemberProjectsUpdateSchema = z.object({
  createdAt: z.string().optional(),
  description: z.string().optional().nullable(),
  endDate: z.string().optional().nullable(),
  id: z.string().optional(),
  mainImageUrl: z.string().optional().nullable(),
  memberGdgId: z.string().optional().nullable(),
  secondaryImageUrl: z.string().optional().nullable(),
  startDate: z.string().optional().nullable(),
  tertiaryImageUrl: z.string().optional().nullable(),
  title: z.string().optional().nullable(),
  updatedAt: z.string().optional().nullable(),
});

export const publicMemberProjectsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("member_projects_memberGdgId_fkey"),
    columns: z.tuple([z.literal("memberGdgId")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("gdg_members"),
    referencedColumns: z.tuple([z.literal("gdg_id")]),
  }),
]);

export const publicMemberShowcaseRowSchema = z.object({
  article_url: z.string(),
  created_at: z.string(),
  date: z.string(),
  description: z.string(),
  id: z.string(),
  showcased_members: z.array(z.string()),
  thumbnail_url: z.string(),
  title: z.string(),
});

export const publicMemberShowcaseInsertSchema = z.object({
  article_url: z.string(),
  created_at: z.string().optional(),
  date: z.string(),
  description: z.string(),
  id: z.string(),
  showcased_members: z.array(z.string()).optional(),
  thumbnail_url: z.string(),
  title: z.string(),
});

export const publicMemberShowcaseUpdateSchema = z.object({
  article_url: z.string().optional(),
  created_at: z.string().optional(),
  date: z.string().optional(),
  description: z.string().optional(),
  id: z.string().optional(),
  showcased_members: z.array(z.string()).optional(),
  thumbnail_url: z.string().optional(),
  title: z.string().optional(),
});

export const publicNfcCardsRowSchema = z.object({
  activated_at: z.string().nullable(),
  created_at: z.string(),
  destination_url: z.string().nullable(),
  gdg_id: z.string(),
  id: z.string(),
  notes: z.string().nullable(),
  revoked_at: z.string().nullable(),
  status: publicNfcCardStatusSchema,
  suspended_at: z.string().nullable(),
  updated_at: z.string(),
});

export const publicNfcCardsInsertSchema = z.object({
  activated_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  destination_url: z.string().optional().nullable(),
  gdg_id: z.string(),
  id: z.string().optional(),
  notes: z.string().optional().nullable(),
  revoked_at: z.string().optional().nullable(),
  status: publicNfcCardStatusSchema.optional(),
  suspended_at: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicNfcCardsUpdateSchema = z.object({
  activated_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  destination_url: z.string().optional().nullable(),
  gdg_id: z.string().optional(),
  id: z.string().optional(),
  notes: z.string().optional().nullable(),
  revoked_at: z.string().optional().nullable(),
  status: publicNfcCardStatusSchema.optional(),
  suspended_at: z.string().optional().nullable(),
  updated_at: z.string().optional(),
});

export const publicNfcCardsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("nfc_cards_gdg_id_fkey"),
    columns: z.tuple([z.literal("gdg_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("gdg_members"),
    referencedColumns: z.tuple([z.literal("gdg_id")]),
  }),
]);

export const publicOneTimePinsRowSchema = z.object({
  created_at: z.string(),
  email: z.string(),
  expires_at: z.string(),
  id: z.string(),
  is_used: z.boolean(),
  otp_code: z.string(),
  reference: z.string(),
});

export const publicOneTimePinsInsertSchema = z.object({
  created_at: z.string().optional(),
  email: z.string(),
  expires_at: z.string(),
  id: z.string().optional(),
  is_used: z.boolean(),
  otp_code: z.string(),
  reference: z.string(),
});

export const publicOneTimePinsUpdateSchema = z.object({
  created_at: z.string().optional(),
  email: z.string().optional(),
  expires_at: z.string().optional(),
  id: z.string().optional(),
  is_used: z.boolean().optional(),
  otp_code: z.string().optional(),
  reference: z.string().optional(),
});

export const publicProductsRowSchema = z.object({
  category: z.string(),
  created_at: z.string(),
  description: z.string(),
  id: z.string(),
  image: z.string(),
  link: z.string().nullable(),
  name: z.string(),
  updated_at: z.string(),
});

export const publicProductsInsertSchema = z.object({
  category: z.string(),
  created_at: z.string().optional(),
  description: z.string(),
  id: z.string().optional(),
  image: z.string(),
  link: z.string().optional().nullable(),
  name: z.string(),
  updated_at: z.string().optional(),
});

export const publicProductsUpdateSchema = z.object({
  category: z.string().optional(),
  created_at: z.string().optional(),
  description: z.string().optional(),
  id: z.string().optional(),
  image: z.string().optional(),
  link: z.string().optional().nullable(),
  name: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicRewardRowSchema = z.object({
  created_at: z.string(),
  description: z.string(),
  id: z.string(),
  is_claimed: z.boolean(),
  title: z.string(),
  user_id: z.string(),
  value: z.number(),
});

export const publicRewardInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string(),
  id: z.string().optional(),
  is_claimed: z.boolean().optional(),
  title: z.string(),
  user_id: z.string(),
  value: z.number(),
});

export const publicRewardUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional(),
  id: z.string().optional(),
  is_claimed: z.boolean().optional(),
  title: z.string().optional(),
  user_id: z.string().optional(),
  value: z.number().optional(),
});

export const publicScrapedGdgEventsRowSchema = z.object({
  attendee_virtual_venue_link: z.string().nullable(),
  cover_image_url: z.string().nullable(),
  created_at: z.string().nullable(),
  description: z.string().nullable(),
  description_short: z.string().nullable(),
  end_date: z.string(),
  event_type: z.string().nullable(),
  event_type_slug: z.string().nullable(),
  gdg_id: z.number(),
  image_square_url: z.string().nullable(),
  is_virtual_event: z.boolean().nullable(),
  last_scraped_at: z.string().nullable(),
  location: z.string().nullable(),
  start_date: z.string(),
  status: z.string().nullable(),
  tags: z.array(z.string()).nullable(),
  title: z.string(),
  total_attendees: z.number().nullable(),
  total_capacity: z.number().nullable(),
  updated_at: z.string().nullable(),
  url: z.string(),
  video_url: z.string().nullable(),
});

export const publicScrapedGdgEventsInsertSchema = z.object({
  attendee_virtual_venue_link: z.string().optional().nullable(),
  cover_image_url: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  description_short: z.string().optional().nullable(),
  end_date: z.string(),
  event_type: z.string().optional().nullable(),
  event_type_slug: z.string().optional().nullable(),
  gdg_id: z.number(),
  image_square_url: z.string().optional().nullable(),
  is_virtual_event: z.boolean().optional().nullable(),
  last_scraped_at: z.string().optional().nullable(),
  location: z.string().optional().nullable(),
  start_date: z.string(),
  status: z.string().optional().nullable(),
  tags: z.array(z.string()).optional().nullable(),
  title: z.string(),
  total_attendees: z.number().optional().nullable(),
  total_capacity: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  url: z.string(),
  video_url: z.string().optional().nullable(),
});

export const publicScrapedGdgEventsUpdateSchema = z.object({
  attendee_virtual_venue_link: z.string().optional().nullable(),
  cover_image_url: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  description_short: z.string().optional().nullable(),
  end_date: z.string().optional(),
  event_type: z.string().optional().nullable(),
  event_type_slug: z.string().optional().nullable(),
  gdg_id: z.number().optional(),
  image_square_url: z.string().optional().nullable(),
  is_virtual_event: z.boolean().optional().nullable(),
  last_scraped_at: z.string().optional().nullable(),
  location: z.string().optional().nullable(),
  start_date: z.string().optional(),
  status: z.string().optional().nullable(),
  tags: z.array(z.string()).optional().nullable(),
  title: z.string().optional(),
  total_attendees: z.number().optional().nullable(),
  total_capacity: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  url: z.string().optional(),
  video_url: z.string().optional().nullable(),
});

export const publicSparkmatesMetricEventsRowSchema = z.object({
  created_at: z.string(),
  gdg_id: z.string(),
  id: z.string(),
  source: publicSparkmatesSourceSchema,
  user_agent: z.string().nullable(),
});

export const publicSparkmatesMetricEventsInsertSchema = z.object({
  created_at: z.string().optional(),
  gdg_id: z.string(),
  id: z.string().optional(),
  source: publicSparkmatesSourceSchema.optional(),
  user_agent: z.string().optional().nullable(),
});

export const publicSparkmatesMetricEventsUpdateSchema = z.object({
  created_at: z.string().optional(),
  gdg_id: z.string().optional(),
  id: z.string().optional(),
  source: publicSparkmatesSourceSchema.optional(),
  user_agent: z.string().optional().nullable(),
});

export const publicSparkmatesMetricEventsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("sparkmates_metric_events_gdg_id_fkey"),
    columns: z.tuple([z.literal("gdg_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("gdg_members"),
    referencedColumns: z.tuple([z.literal("gdg_id")]),
  }),
]);

export const publicSurveyRowSchema = z.object({
  attendance_code: z.string().nullable(),
  close_time: z.string().nullable(),
  created_at: z.string(),
  event_id: z.string(),
  id: z.string(),
  is_active: z.boolean(),
  questions_schema: jsonSchema.nullable(),
  slug: z.string(),
  updated_at: z.string(),
});

export const publicSurveyInsertSchema = z.object({
  attendance_code: z.string().optional().nullable(),
  close_time: z.string().optional().nullable(),
  created_at: z.string().optional(),
  event_id: z.string(),
  id: z.string().optional(),
  is_active: z.boolean().optional(),
  questions_schema: jsonSchema.optional().nullable(),
  slug: z.string(),
  updated_at: z.string().optional(),
});

export const publicSurveyUpdateSchema = z.object({
  attendance_code: z.string().optional().nullable(),
  close_time: z.string().optional().nullable(),
  created_at: z.string().optional(),
  event_id: z.string().optional(),
  id: z.string().optional(),
  is_active: z.boolean().optional(),
  questions_schema: jsonSchema.optional().nullable(),
  slug: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicSurveyRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("survey_event_id_fkey"),
    columns: z.tuple([z.literal("event_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("event"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicSurveyResponseRowSchema = z.object({
  certificate_url: z.string().nullable(),
  created_at: z.string(),
  email: z.string(),
  event_id: z.string(),
  gdg_id: z.string().nullable(),
  id: z.string(),
  survey_data: jsonSchema,
  survey_id: z.string(),
});

export const publicSurveyResponseInsertSchema = z.object({
  certificate_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  email: z.string(),
  event_id: z.string(),
  gdg_id: z.string().optional().nullable(),
  id: z.string().optional(),
  survey_data: jsonSchema,
  survey_id: z.string(),
});

export const publicSurveyResponseUpdateSchema = z.object({
  certificate_url: z.string().optional().nullable(),
  created_at: z.string().optional(),
  email: z.string().optional(),
  event_id: z.string().optional(),
  gdg_id: z.string().optional().nullable(),
  id: z.string().optional(),
  survey_data: jsonSchema.optional(),
  survey_id: z.string().optional(),
});

export const publicSurveyResponseRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("survey_response_event_id_fkey"),
    columns: z.tuple([z.literal("event_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("event"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("survey_response_survey_id_fkey"),
    columns: z.tuple([z.literal("survey_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("survey"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicTaskRowSchema = z.object({
  completed_at: z.string().nullable(),
  created_at: z.string().nullable(),
  description: z.string().nullable(),
  id: z.string(),
  is_completed: z.boolean().nullable(),
  name: z.string().nullable(),
  points_on_completion: z.number().nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const publicTaskInsertSchema = z.object({
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  is_completed: z.boolean().optional().nullable(),
  name: z.string().optional().nullable(),
  points_on_completion: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const publicTaskUpdateSchema = z.object({
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  is_completed: z.boolean().optional().nullable(),
  name: z.string().optional().nullable(),
  points_on_completion: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicTeamRowSchema = z.object({
  description: z.string(),
  id: z.string(),
  name: z.string(),
  parent_team_id: z.string().nullable(),
  responsibilities: z.string().nullable(),
});

export const publicTeamInsertSchema = z.object({
  description: z.string(),
  id: z.string().optional(),
  name: z.string(),
  parent_team_id: z.string().optional().nullable(),
  responsibilities: z.string().optional().nullable(),
});

export const publicTeamUpdateSchema = z.object({
  description: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  parent_team_id: z.string().optional().nullable(),
  responsibilities: z.string().optional().nullable(),
});

export const publicTeamRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("team_parent_team_id_fkey"),
    columns: z.tuple([z.literal("parent_team_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("team"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicTeamMemberRowSchema = z.object({
  id: z.string(),
  role: z.string(),
  team_id: z.string(),
  user_id: z.string(),
});

export const publicTeamMemberInsertSchema = z.object({
  id: z.string().optional(),
  role: z.string(),
  team_id: z.string(),
  user_id: z.string(),
});

export const publicTeamMemberUpdateSchema = z.object({
  id: z.string().optional(),
  role: z.string().optional(),
  team_id: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicTeamMemberRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("team_member_team_id_fkey"),
    columns: z.tuple([z.literal("team_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("team"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("team_member_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("gdg_members"),
    referencedColumns: z.tuple([z.literal("gdg_id")]),
  }),
]);

export const publicUserAchievementRowSchema = z.object({
  achieved_at: z.string().nullable(),
  created_at: z.string().nullable(),
  description: z.string().nullable(),
  id: z.string(),
  image_url: z.string().nullable(),
  title: z.string(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const publicUserAchievementInsertSchema = z.object({
  achieved_at: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  title: z.string(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const publicUserAchievementUpdateSchema = z.object({
  achieved_at: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  title: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicUserCertificateRowSchema = z.object({
  description: z.string(),
  id: z.string(),
  image_url: z.string().nullable(),
  title: z.string(),
  user_id: z.string(),
});

export const publicUserCertificateInsertSchema = z.object({
  description: z.string(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  title: z.string(),
  user_id: z.string(),
});

export const publicUserCertificateUpdateSchema = z.object({
  description: z.string().optional(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  title: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicUserCredentialRowSchema = z.object({
  created_at: z.string(),
  email_address: z.string(),
  id: z.string(),
  password_hash: z.string(),
  updated_at: z.string(),
  username: z.string(),
});

export const publicUserCredentialInsertSchema = z.object({
  created_at: z.string().optional(),
  email_address: z.string(),
  id: z.string().optional(),
  password_hash: z.string(),
  updated_at: z.string().optional(),
  username: z.string(),
});

export const publicUserCredentialUpdateSchema = z.object({
  created_at: z.string().optional(),
  email_address: z.string().optional(),
  id: z.string().optional(),
  password_hash: z.string().optional(),
  updated_at: z.string().optional(),
  username: z.string().optional(),
});

export const publicUserCredentialReferenceCodeRowSchema = z.object({
  created_at: z.string().nullable(),
  email_address: z.string().nullable(),
  id: z.string(),
  otp_reference: z.string().nullable(),
  payload: jsonSchema.nullable(),
  reference_code: z.string(),
  type: z.string().nullable(),
});

export const publicUserCredentialReferenceCodeInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  email_address: z.string().optional().nullable(),
  id: z.string().optional(),
  otp_reference: z.string().optional().nullable(),
  payload: jsonSchema.optional().nullable(),
  reference_code: z.string(),
  type: z.string().optional().nullable(),
});

export const publicUserCredentialReferenceCodeUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  email_address: z.string().optional().nullable(),
  id: z.string().optional(),
  otp_reference: z.string().optional().nullable(),
  payload: jsonSchema.optional().nullable(),
  reference_code: z.string().optional(),
  type: z.string().optional().nullable(),
});

export const publicUserProjectRowSchema = z.object({
  created_at: z.string(),
  demo_url: z.string().nullable(),
  description: z.string().nullable(),
  id: z.string(),
  repo_url: z.string().nullable(),
  tech_stack: z.string().nullable(),
  title: z.string(),
  user_id: z.string(),
});

export const publicUserProjectInsertSchema = z.object({
  created_at: z.string().optional(),
  demo_url: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  repo_url: z.string().optional().nullable(),
  tech_stack: z.string().optional().nullable(),
  title: z.string(),
  user_id: z.string(),
});

export const publicUserProjectUpdateSchema = z.object({
  created_at: z.string().optional(),
  demo_url: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  repo_url: z.string().optional().nullable(),
  tech_stack: z.string().optional().nullable(),
  title: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicUserRoleRowSchema = z.object({
  description: z.string(),
  id: z.string(),
  name: z.string(),
});

export const publicUserRoleInsertSchema = z.object({
  description: z.string(),
  id: z.string().optional(),
  name: z.string(),
});

export const publicUserRoleUpdateSchema = z.object({
  description: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
});

export const publicUserRoleJunctionRowSchema = z.object({
  gdg_id: z.string(),
  role_id: z.string(),
});

export const publicUserRoleJunctionInsertSchema = z.object({
  gdg_id: z.string(),
  role_id: z.string(),
});

export const publicUserRoleJunctionUpdateSchema = z.object({
  gdg_id: z.string().optional(),
  role_id: z.string().optional(),
});

export const publicUserRoleJunctionRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("user_role_junction_gdg_id_fkey"),
    columns: z.tuple([z.literal("gdg_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("gdg_members"),
    referencedColumns: z.tuple([z.literal("gdg_id")]),
  }),
  z.object({
    foreignKeyName: z.literal("user_role_junction_role_id_fkey"),
    columns: z.tuple([z.literal("role_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_role"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicUserRolePermissionRowSchema = z.object({
  action: z.string(),
  resource: z.string(),
  role_id: z.string(),
});

export const publicUserRolePermissionInsertSchema = z.object({
  action: z.string(),
  resource: z.string(),
  role_id: z.string(),
});

export const publicUserRolePermissionUpdateSchema = z.object({
  action: z.string().optional(),
  resource: z.string().optional(),
  role_id: z.string().optional(),
});

export const publicUserRolePermissionRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("user_role_permission_role_id_fkey"),
    columns: z.tuple([z.literal("role_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("user_role"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicUserSettingsRowSchema = z.object({
  color_theme: z.boolean(),
  id: z.string(),
  user_id: z.string(),
});

export const publicUserSettingsInsertSchema = z.object({
  color_theme: z.boolean(),
  id: z.string().optional(),
  user_id: z.string(),
});

export const publicUserSettingsUpdateSchema = z.object({
  color_theme: z.boolean().optional(),
  id: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicWalletRowSchema = z.object({
  balance: z.number(),
  created_at: z.string(),
  id: z.string(),
  spark_points: z.number(),
  updated_at: z.string(),
  user_id: z.string(),
  webdev_points: z.number().nullable(),
});

export const publicWalletInsertSchema = z.object({
  balance: z.number(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  spark_points: z.number().optional(),
  updated_at: z.string().optional(),
  user_id: z.string(),
  webdev_points: z.number().optional().nullable(),
});

export const publicWalletUpdateSchema = z.object({
  balance: z.number().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  spark_points: z.number().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
  webdev_points: z.number().optional().nullable(),
});

export const publicWalletTransactionRowSchema = z.object({
  amount: z.number(),
  created_at: z.string(),
  id: z.string(),
  point_type: z.string().nullable(),
  source_id: z.string(),
  source_type: z.string(),
  user_id: z.string(),
});

export const publicWalletTransactionInsertSchema = z.object({
  amount: z.number().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  point_type: z.string().optional().nullable(),
  source_id: z.string(),
  source_type: z.string(),
  user_id: z.string(),
});

export const publicWalletTransactionUpdateSchema = z.object({
  amount: z.number().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  point_type: z.string().optional().nullable(),
  source_id: z.string().optional(),
  source_type: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicFlatSurveyDataRowSchema = z.object({
  college: z.string().nullable(),
  comments_for_speakers: z.string().nullable(),
  created_at: z.string().nullable(),
  id: z.string().nullable(),
  is_pupian: z.boolean().nullable(),
  missing_content: z.string().nullable(),
  name: z.string().nullable(),
  organization: z.string().nullable(),
  overall_satisfaction: z.number().nullable(),
  program: z.string().nullable(),
  questions_for_speakers: z.string().nullable(),
  rating_duration: z.number().nullable(),
  rating_program_flow: z.number().nullable(),
  rating_schedule: z.number().nullable(),
  rating_speakers: z.number().nullable(),
  rating_subject: z.number().nullable(),
  suggestions: z.string().nullable(),
  valuable_aspects: z.string().nullable(),
  year_level: z.string().nullable(),
});

export const publicFlatSurveyDataInsertSchema = z.object({
  college: z.never().optional(),
  comments_for_speakers: z.never().optional(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  is_pupian: z.never().optional(),
  missing_content: z.never().optional(),
  name: z.never().optional(),
  organization: z.never().optional(),
  overall_satisfaction: z.never().optional(),
  program: z.never().optional(),
  questions_for_speakers: z.never().optional(),
  rating_duration: z.never().optional(),
  rating_program_flow: z.never().optional(),
  rating_schedule: z.never().optional(),
  rating_speakers: z.never().optional(),
  rating_subject: z.never().optional(),
  suggestions: z.never().optional(),
  valuable_aspects: z.never().optional(),
  year_level: z.never().optional(),
});

export const publicFlatSurveyDataUpdateSchema = z.object({
  college: z.never().optional(),
  comments_for_speakers: z.never().optional(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  is_pupian: z.never().optional(),
  missing_content: z.never().optional(),
  name: z.never().optional(),
  organization: z.never().optional(),
  overall_satisfaction: z.never().optional(),
  program: z.never().optional(),
  questions_for_speakers: z.never().optional(),
  rating_duration: z.never().optional(),
  rating_program_flow: z.never().optional(),
  rating_schedule: z.never().optional(),
  rating_speakers: z.never().optional(),
  rating_subject: z.never().optional(),
  suggestions: z.never().optional(),
  valuable_aspects: z.never().optional(),
  year_level: z.never().optional(),
});

export const publicSparkmatesScanCountsRowSchema = z.object({
  gdg_id: z.string().nullable(),
  scan_count: z.number().nullable(),
  source: publicSparkmatesSourceSchema.nullable(),
});

export const publicSparkmatesScanCountsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("sparkmates_metric_events_gdg_id_fkey"),
    columns: z.tuple([z.literal("gdg_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("gdg_members"),
    referencedColumns: z.tuple([z.literal("gdg_id")]),
  }),
]);

export const publicGetSparkmatesAnalyticsArgsSchema = z.object({
  p_gdg_id: z.string(),
});

export const publicGetSparkmatesAnalyticsReturnsSchema = z.array(
  z.object({
    scan_count: z.number(),
    source: publicSparkmatesSourceSchema,
  }),
);

export const publicVerifyMemberArgsSchema = z.object({
  search_term: z.string(),
});

export const publicVerifyMemberReturnsSchema = z.array(
  z.object({
    avatar_image_url: z.string().nullable(),
    bio: z.string().nullable(),
    created_at: z.string().nullable(),
    department: z.string().nullable(),
    display_name: z.string().nullable(),
    email: z.string(),
    first_name: z.string().nullable(),
    gdg_id: z.string(),
    github_url: z.string().nullable(),
    is_public: z.boolean().nullable(),
    last_name: z.string().nullable(),
    learning_interests: z.string().nullable(),
    linkedin_url: z.string().nullable(),
    membership_type: z.string().nullable(),
    middle_name: z.string().nullable(),
    nickname: z.string().nullable(),
    other_links: z.string().nullable(),
    portfolio_url: z.string().nullable(),
    program: z.string().nullable(),
    section_order: z.string().nullable(),
    skills_summary: z.string().nullable(),
    suffix: z.string().nullable(),
    technical_skills: z.string().nullable(),
    tools_and_technologies: z.string().nullable(),
    updated_at: z.string().nullable(),
    year_level: z.number().nullable(),
  }),
);
