import { describe, expect, it, beforeEach } from "vitest";
import { MockFileRepository } from "../infrastructure/MockFileRepository";
import { MockFileStorage } from "../infrastructure/MockFileStorage";
import { UploadFile } from "../useCases/UploadFile";
import { FileBuffer } from "../domain/FileBuffer";
import { IFileRepository } from "../domain/IFileRepository";
import { IFileStorage } from "../domain/IFileStorage";

let fileRepository: IFileRepository;
let fileStorage: IFileStorage;
let uploadFileUseCase: UploadFile;

const initializeInstances = () => {
  fileRepository = new MockFileRepository();
  fileStorage = new MockFileStorage();
  uploadFileUseCase = new UploadFile(fileStorage, fileRepository);
};

describe("UploadFile Use Case", () => {
  beforeEach(initializeInstances);

  it("uploads a file and persists the record", async () => {
    const fileBuffer = new FileBuffer(new ArrayBuffer(8), "nexus-logo.png", "image/png");
    
    const result = await uploadFileUseCase.execute(
      fileBuffer,
      "Nexus Logo",
      "The official project logo",
      "branding/logos"
    );

    // Check if it returned a valid FileRecord
    expect(result.props.id).toBeDefined();
    expect(result.props.fileName).toBe("Nexus Logo");
    
    // Check if previewUrl was generated by MockFileStorage
    expect(result.props.previewUrl).toContain("http"); 
    expect(result.props.storageReference).toBeDefined();

    // Verify it actually exists in the repository
    const storedFile = await fileRepository.findById(result.props.id);
    expect(storedFile).not.toBeNull();
    expect(storedFile?.props.fileName).toBe("Nexus Logo");
  });
});