import { auth } from "#models/authSystem/index.js";
import { SchemaFactory } from "#utils/schemaFactory.utils.js";

export const body = SchemaFactory.Request.withPayload(auth.verifyEmailRequest);

export const response = {
  200: SchemaFactory.Response.single(auth.verificationResponse),
  ...SchemaFactory.Response.standardErrors(),
};

export const docs_summary = "Verify email with token";

export const docs_description =
  "Verifies a user's email using the token hash generated by Supabase.";

export const docs_body = {
  data: {
    token_hash: "The token hash from the email link",
    type: "The type of verification (signup, magiclink, etc.)",
  },
};

export const docs_response_200 =
  "Successfully verified email and returned user session";
