import { cz } from "@packages/typed-rest/shared";

/**
 * Represents a basic enriched member info for showcase.
 */
export const showcasedMemberEnriched = cz.object({
  gdgId: cz.string(),
  displayName: cz.string().nullable(),
  firstName: cz.string(),
  lastName: cz.string(),
  fullName: cz.string(),
  avatarUrl: cz.string().nullable(),
  program: cz.string().nullable(),
  yearLevel: cz.number().nullable(),
});

/**
 * Represents a Member Showcase record in the system.
 */
export const memberShowcaseRecord = cz.object({
  id: cz.string(),
  thumbnailUrl: cz.string(),
  title: cz.string(),
  date: cz.string(),
  description: cz.string(),
  articleUrl: cz.string(),
  showcasedMembers: cz.array(showcasedMemberEnriched),
  createdAt: cz.string(),
});

/**
 * Data Transfer Object for creating a new Member Showcase.
 * Excludes fields generated by the application/database.
 */
export const memberShowcaseRecordInsertDTO = cz.object({
  title: cz.string(),
  date: cz.string(),
  description: cz.string(),
  articleUrl: cz.string(),
  showcasedMembers: cz.array(cz.string()),
});

/**
 * Data Transfer Object for updating an existing Member Showcase.
 */
export const memberShowcaseRecordUpdateDTO = memberShowcaseRecordInsertDTO.partial();
