import { cz } from "@packages/typed-rest/shared";

/**
 * Represents a Member Showcase record in the system.
 */
export const memberShowcaseRecord = cz.object({
  id: cz.string(),
  thumbnailUrl: cz.string(),
  title: cz.string(),
  date: cz.string(),
  description: cz.string(),
  articleUrl: cz.string(),
  showcasedMembers: cz.array(cz.string()),
  createdAt: cz.string(),
});

/**
 * Data Transfer Object for creating a new Member Showcase.
 * Excludes fields generated by the application/database.
 */
export const memberShowcaseRecordInsertDTO = memberShowcaseRecord.omit({
  id: true,
  thumbnailUrl: true,
  createdAt: true,
});

/**
 * Data Transfer Object for updating an existing Member Showcase.
 */
export const memberShowcaseRecordUpdateDTO = memberShowcaseRecordInsertDTO.partial();
