import { cz } from "@packages/typed-rest/shared";

/**
 * Represents a GDG Member record in the system.
 */
export const gdgMemberRecord = cz.object({
  gdgId: cz.string(),
  email: cz.string().email(),
  membershipType: cz.string().nullable(),
  avatarUrl: cz.string().url().nullable(),
  program: cz.string().nullable(),
  yearLevel: cz.number().nullable(),
  department: cz.string().nullable(),
  displayName: cz.string().nullable(),
  firstName: cz.string(),
  middleName: cz.string().nullable(),
  lastName: cz.string(),
  suffix: cz.string().nullable(),
  bio: cz.string().nullable(),
  githubUrl: cz.string().url().nullable(),
  linkedinUrl: cz.string().url().nullable(),
  portfolioWebsiteUrl: cz.string().url().nullable(),
  otherLinks: cz.array(cz.string()),
  technicalSkills: cz.array(cz.string()),
  learningInterests: cz.array(cz.string()),
  toolsAndTechnologies: cz.array(cz.string()),
  isPublic: cz.boolean(),
});

/**
 * Data Transfer Object for creating a new GDG Member.
 * Excludes fields generated by the application/database.
 */
export const gdgMemberRecordInsertDTO = gdgMemberRecord.omit({
  gdgId: true,
});

/**
 * Data Transfer Object for updating an existing GDG Member.
 */
export const gdgMemberRecordUpdateDTO = gdgMemberRecordInsertDTO.partial();
