name: CI Build & Test

on:
  push:
    branches: [deploy-develop, staging, main]
  pull_request:
    branches: [staging, main]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/tests
